Repository exercism/fsharp, pull requests merged in 2021-11, with the labels that each got.

#1009 Implement new Concept Exercise: tuples
  concepts/tuples/.meta/config.json
  concepts/tuples/about.md
  concepts/tuples/introduction.md
  concepts/tuples/links.json
  config.json
  exercises/Exercises.sln
  exercises/concept/tisbury-treasure-hunt/.docs/hints.md
  exercises/concept/tisbury-treasure-hunt/.docs/instructions.md
  exercises/concept/tisbury-treasure-hunt/.docs/introduction.md
  exercises/concept/tisbury-treasure-hunt/.meta/Exemplar.fs
  exercises/concept/tisbury-treasure-hunt/.meta/config.json
  exercises/concept/tisbury-treasure-hunt/.meta/design.md
  exercises/concept/tisbury-treasure-hunt/TisburyTreasureHunt.fs
  exercises/concept/tisbury-treasure-hunt/TisburyTreasureHunt.fsproj
  exercises/concept/tisbury-treasure-hunt/TisburyTreasureHuntTests.fs
Labels: x:size/large

#1033 Remove unnecessary use of 'rec' keyword
  concepts/lists/about.md
  concepts/lists/introduction.md
  exercises/concept/tracks-on-tracks-on-tracks/.docs/introduction.md
Labels: x:size/small

#1023 🤖 Remove obsolete `maintainers.json` file
  .github/CODEOWNERS
  config/maintainers.json
Labels: x:size/tiny

#1040 Update tisbury-treasure-hunt instructions to match with provided tests
  exercises/concept/tisbury-treasure-hunt/.docs/instructions.md
Labels: x:size/small
